
type = "Agent"
task = '''根据需求制定迁移方案'''
[manager]
max_turns = 10
mode = 'Questionnaire'
participants = ["assistant"]
questions = ["为了实现以上目标， 哪些模块或类与任务的相关性强",
    "这些类或模块中， 哪些函数与任务的相关性强 ",
    "总结具体需要迁移的函数 (格式：class::function )",
    "cuda迁移时要求保持与原始代码的接口兼容，应该如何设计，举例说明"
]

summary_prompt = '''
1. 输出备份puml文件(文件地址)
2. 总结具体的技术方案

技术方案内容格式：
## 目标
xxx

## 涉及迁移模块，类， 函数(矫正后的函数名，滤除不存在函数)
- class1 :: function1 : 说明
- class2 :: function2 : 说明
- class3 :: function3 : 说明

## 接口兼容的迁移方案说明
xxx


'''


[[agents]]
name = "assistant"
tools = ["run_shell_code","get_dir_structure_with_tree_cmd","find_declaration" ]
system_prompt = '''
角色：架构师
职责：
1. 利用项目的系统架构，完成新需求的方案设计
'''

