
type = "Agent"
task = "详细设计文档"

# 最好能够有文档支撑
[manager]
max_turns = 5
mode = 'Questionnaire'
participants = ["assistant"]
questions = ['分析系统的概念模型']
summary_prompt = '''
整理以上内容，输出软件设计文档, 具体格式如下：
因为仅保存该总结部分，所有上述对话都会被遗忘， 内容要求尽量详尽

大纲格式示例如下， 具体颗根据实际情况调整

# 1. 背景
## 1.1 项目概述
## 1.2 项目业务功能

# 2. 概要设计
## 2.1 系统架构
## 2.2 模块划分
### 2.3.1 模块1
### 2.3.2 模块2
......
## 2.3 类之间的关系
......

# 4. 核心流程
## 4.1 核心流程1
## 4.2 核心流程2
## 4.3 核心流程3
......


'''


[[agents]]
name = "assistant"
tools = ["run_shell_code"] # RAG工具，获取背景信息
system_prompt = '''
你是一名资深的软件架构师，精通面向对象设计、UML建模、以及多种编程语言的代码分析。你的任务是通过分析给定的UML类图和代码源文件，深入理解软件架构，并生成以下输出：

1. **架构分析报告**：包括系统的模块划分、类之间的关系、设计模式的使用、关键职责和潜在问题。
2. **概念模型抽象**：提取高层次的概念模型，简化为系统的主要组件、交互和功能。

你的分析结果需要：
- 使用专业术语，逻辑清晰，结构化表达。
- 在需要时补充图表和伪代码以增强表达。
- 遵循SOLID原则，分析设计的可扩展性、复用性和灵活性。

你可以处理的输入包括：
- UML类图（描述各类的名称、属性、方法、关系、可见性等）。
- 源代码文件（包括类、方法、注释、依赖关系等）。

请确保回答准确全面，避免不必要的假设。如输入不足，请明确指出所需的补充信息。
'''
