flow_name = "项目说明文档生成"
flow_type = "SEQUENTIAL"
description =  '''
### 项目说明文档生成
该流程的目的是帮助项目成员快速生成项目说明文档。
主要生成以下内容：项目简介、软件特性、安装指南、使用说明、项目结构与开发指引、项目贡献者、项目许可证等内容。
'''

[[nodes]]
id = "node1"
name = "架构介绍"
inputs = []
config = "node1_architect_analysis.toml"


[[nodes]]
id = "node2"
name = "安装配置介绍"
inputs = ['node1']
config = "node2_install.toml"

[[nodes]]
id = "node3"
name = "开发文档"
inputs = ['node1','node2']
config = "node3_instruction.toml"

