project_name = "ArCTIc算法CUDA加速"
project_id = "project_2"
description = '''AlgoRithm for Charge Transfer Inefficiency (CTI) correction。
Add or remove image trails due to charge transfer inefficiency in CCD detectors by modelling the trapping, releasing, and moving of charge along pixels.
'''
workspace_path = "workspace/arctic"
llm_config = "docs/OAI_CONFIG_LIST.json"

requirement = '''
ArCTIc算法采用c++实现，存在高计算量的部分，特别是TrapManagerInstantCapture::n_electrons_released， 通过CUDA加速提高算法的运行速度。
'''
requirement_flow = ['flow2']


[codebase]
language = "C++"
project_path = "/home/jiangbo/arctic/"
source_path = "/home/jiangbo/arctic/src/"
header_path = "/home/jiangbo/arctic/include/"
build_path = "/home/jiangbo/arctic/build/"
namespace = ''


[[flows]]
flow_name = "架构理解"
flow_id = "flow1"
config = "workflows/cuda_migration/flow1_architect_understand/flow_architect_understand.toml"
previous_flows = []


[[flows]]
flow_name = "迁移方案"
flow_id = "flow2"
config = "workflows/cuda_migration/flow2_solution/flow_solution.toml"
previous_flows = ["flow1"]

[[flows]]
flow_name = "任务分解"
flow_id = "flow3"
config = "workflows/cuda_migration/flow3_task_decomposition/flow_task_decomposition.toml"
previous_flows = ["flow2"]


[[flows]]
flow_name = "任务执行"
flow_id = "flow4"
config = "workflows/cuda_migration/flow4_task_execution/flow_task_execution.toml"
previous_flows = ["flow3"]