type = "Agent"
task = ''' 对待迁移模块进行筛选，留下具备重要迁移价值的模块与函数 '''

[manager]
max_turns = 5
mode = 'Questionnaire'
questions = [
    '结合CUDA迁移价值评价，重新整理待迁移模块，留下具备CUDA迁移价值的模块与函数',
    '检查各模块的函数列表，判断其依赖函数中是否遗漏具备CUDA迁移价值的函数，将其补上',
]
participants = ["assistant"]

summary_prompt = '''
汇总以上内容，输出具备CUDA迁移价值的模块与函数，按模块/类排序输出
函数在前述模块中已经出现，则不需要重复列出

### 模块1
- class1::function1
- class1::function2
- class1::function3

### 模块2
- class2::functionA
- class2::functionB

'''


[[agents]]
name = "assistant"
tools = [] 
system_prompt = '''
角色：开发工程师
'''




