type = "Agent"
task = '''围绕cuda迁移解决方案，制定具体的迁移函数清单'''

[manager]
max_turns = 5
mode = 'Questionnaire'
questions = [
    "为了能够实现计算加速，需要对主要函数进行cuda加速。输出需要进行CUDA迁移的函数清单(函数格式class::function)",
    '查询函数清单中涉及类的派生类信息',
    '结合迁移函数清单 与 派生类信息， 形成更加完整的待CUDA迁移的函数清单（全部可能的函数）',
    "利用query_right_name, 矫正所有待迁移的函数名清单，滤除不存在的函数",
    "利用query_important_functions, 查询所有待迁移函数的所依赖的重要中间或基础函数",
]
participants = ["assistant"]

summary_prompt = '''
汇总待迁移的函数及其依赖的重要函数，（被依赖的模块前置）
格式如下：
### 函数清单（待CUDA迁移）
- class::function1
- class::function2
- class::function3



'''


[[agents]]
name = "assistant"
tools = ['extract_Inheritance_classes_from_uml', 'query_right_name','query_important_functions'] 
system_prompt = '''
角色：开发工程师
'''




