flow_name = "代码执行"
flow_type = "LOOP"
description =  '''
## 任务执行
当前工作流的目标是执行任务，完成目标函数或者模块的代码CUDA迁移工作，包括代码查询，代码生成，代码编辑，代码构建与调试。
'''
# 循环执行参数
[loop]
dependencies = ['flow3.node8']
mode = "Iteration"
prompt = "将任务分解，将需要迁移的模块，根据要求格式化输出，形成任务列表，便于后续遍历执行。每个子任务请详细描述任务内容"


[[nodes]]
id = "node1"
name = "任务相关代码查询"
inputs = []
config = "node1_config_QueryCode.toml"

[[nodes]]
id = "node2"
name = "代码生成"
inputs = ["node1"]
config = "node2_config_genCode.toml"

[[nodes]]
id = "node3"
name = "编辑代码"
inputs = ["node2"]
config = "node3_config_editCode.toml"

[[nodes]]
id = "node4"
name = "构建调试"
inputs = ["node3"]
config = "node4_config_debugCode.toml"
