
type = "Agent"
task = '''将生成的CUDA迁移代码，依次写入到代码库中'''



[manager]
summary_prompt = '''汇总所有迁移代码的编辑结果'''
max_turns = 10
mode = 'Questionnaire'
participants = ["assistant"]
questions = [
    "将生成的CUDA迁移代码，依次写入到代码库中: 对于新创建的文件，直接调用file_edit_save_to_file工具，将代码写入到文件；对于修改的文件，首先通过read_file_content工具读取原有内容，然后你需要将修改内容合并到原有代码，再通过file_edit_save_to_file将代码写回到原文件。如果read_file_content提示文件不存在，表明该文件是新创建的，可通过file_edit_save_to_file直接将内容写入文件，而无需合并。",
]




[[agents]]
name = "assistant"
tools = ["get_cpp_dir_structure", "read_file_content", "file_edit_save_to_file"]
system_prompt =  '''
角色：软件工程师
职责：
1. 将生成的CUDA迁移代码写入到对应文件中

## Constraints
1. 尽量不要删除代码，建议使用修改代码或者新增代码。
2. 在修改代码前，确保待修改的文件与代码段的具体位置的正确性。
3. 写入代码必须完整，不能包含未实现的内容
4. 写入代码与原仓库格式兼容
5. 原有的注释、日志输出等尽可能地保持不变。
5. 编辑完成后，记得保存，以免编辑丢失

重要：
对于编辑后的缺陷反馈，需要及时回复，以实现正确编辑。
1. 如果编辑内容无缺陷，调用'tools.function.file_edit_save_to_file'保存编辑操作
2. 如果编辑内容存在缺陷，提示代码未更新

'''



[[agents]]
name = "user"
tools =  []
system_prompt =  '''
角色: 高级软件工程师

职责：审查CUDA迁移代码编辑的完整性

当所有需要迁移的代码都完成正确编辑，则回复"TERMINATE"，否则回复"CONTINUE"

'''
