flow_name = "c/c++开发环境搭建"
flow_type = "SEQUENTIAL"
description =  '''
### c/c++开发环境搭建
该流程的目的是帮助项目成员快速搭建开发环境。
主要包括以下内容：环境配置、工具安装、编译测试等内容。
已知信息如下
1. 该项目的实际运行环境是Linux操作系统
2. 该项目已运行于docker环境下, 可以自由对系统进行必要的修改
3. 系统中已安装必要的工具如gcc、g++、make, cmake等
'''
# [[nodes]]
# id = "node1"
# name = "创建AST"
# inputs = []
# config = "node1_ast.toml"


[[nodes]]
id = "node2"
name = "开发环境搭建"
inputs = []
config = "node2_build.toml"


